language: objective-c
rvm:
  - 2.4.1
cache: bundler

# Whitelist `master` branch as the only branch to build pushes for.
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+(-(beta|alpha|RC)\d*)?/ # Regex to trigger builds for git tags so that we can deploy docs to gh-pages.
matrix:
  include:
      # Xcode9
    - osx_image: xcode9.3beta
      env: SDK=iphonesimulator PLATFORM="iOS Simulator,name=iPhone 6s,OS=11.3" SCHEME=Contentful_iOS
    - osx_image: xcode9.3beta
      env: SDK=appletvsimulator PLATFORM="tvOS Simulator,name=Apple TV 1080p,OS=11.0" SCHEME=Contentful_tvOS
    - osx_image: xcode9.3beta
      env: SDK=macosx PLATFORM="OS X" SCHEME=Contentful_macOS
    - osx_image: xcode9
      env: SWIFT_BUILD=true
      
script:
  - ./Scripts/travis-build-test.sh
after_success:
  - ./Scripts/integration-test.sh
  - bundle exec slather coverage -s --coveralls
  - bundle exec pod lib lint Contentful.podspec
  # Build the docs only for one of the jobs
  - if [[ $TRAVIS_PULL_REQUEST == false && -n $TRAVIS_TAG  && $SWIFT_BUILD == true ]]; then ./Scripts/reference-docs.sh; fi

# Deploy the docs to GH pages if we are pushing a tag
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  local_dir: docs
  on:
    condition: $TRAVIS_PULL_REQUEST == false && -n $TRAVIS_TAG && $SWIFT_BUILD == true

env:
  global:
    - secure: JLkG75LSPkXdxZ4DRmjdvcie+YbOx1mkf2b7Ddny4dFYivw1nAQtJYTsqgog/hYwzxxGYD+93DiXkm4ElvxwHLq19s4aCuQY3uu3PO/N8gTqcJpsGfcFFkyqhEjpKrJKuWtLLS78CjXnfeRvIT7wT0nySvqotRZ4pOGZnCiEqOkGXjUv/eI9d4YZu4VVu46OMS27kTOV7CoeHhWiXV5L+owU8t3gffIpuuhkKr4LDtl/VhjdVmmwwDWjEfSNflCo0T/XiFNEF5mmF86BI5njjU0RVzmcRwWOjqgvA0nrvarae6SVn/QZC6JZutG+pKWWoSOAollbAXwjxcLIYMF/wIRXc3NJrS4VGW+Z2ORojcdbosoohPVrnayOy4Szq+I8Afa1dIQ+vYq2JxWuaOA2X+Toy9m81svIaE7CLNMK52aA0z8fOQFwFUAmFGOKVtHtiYkHcItUuFk7+c0feekfvmDsawtgACXTIUua6DIq0g54QTc9PidxGQti2kXoqRBaKzpGSbbMHIxh0A6wnPw9r/+26y8nipATNBmKbkwKOuLm6M4eMKRpvGNncv9z4zM66DAQH8EA5A92Qt9g1ETXeC+R9+SUd8r8ryFr/hr0jpjXEuk0aanM7BuLAjCFDXdQKFbjOtpR0ary6GNQK0FdGSmxKku1CXaUH9gNWg1cKpU=
    - secure: gpYcun1Nr0aDkggVr3OhR16gopoiOIVTUnk6oYFBmFWQDWPxzWOb5lc+oz5TJIhER5b1J6vl7sSXq8hAybBdy5fDRDHhJ7t5DvNc3DWhhTUr11gLzhG2kkCuKemMhJXR87l0+Kz94NfVmnJKw8TEfetrc6/cpJnQSYBjIfEZkdxkIy35jLt5AOeEyokchJg75891mtkcZa69iOBqf9tBhPAOigQQmAzVkKbxgkz0WA69KhhankJbZuOmySpTrWxFI/slz8j+Dj1wAcLqqbHWajjThJzBWXupg2CugyASuVBtQPJgKP9wo/F5dIDY/LreXoJUbfrxcEjLc54SX5A3cuq//H6/EDMGOxTr3YyhxL/Ba4r9nZomT1CwcRd2vrWPDmfnOtaImNzbhZxpU7O3M6kOwwnZD7Bl2isPer0sMuBfqdsL04HdQJIKZSrjgsGPKf6Ss2GKKKZIdGHX/i3X2c+S7cph5Vw/42I56WvRMm5S/7jn7DYTgZTAYN2plWrYSdjiVlXjsfz4aR1SEYzcIQ8Gh/J+ZOK2t0OkIqDvdQT+hKTUOCtBN7MSzGNRhfoQghKIETz6M9VlNCJ3yG3O3eMEi7UcozNKRrTGzULtWqp9Dmw9Pkb3xYWVaCLFW2GWPUaM7n7td7kBsubEIYzkz7I+KqhPMoesl/UYMSTaFYU=

