language: objective-c
osx_image: xcode8.1
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
script:
  - ./Scripts/travis-build-test.sh
after_success:
  - bundle exec slather coverage
  - pod lib lint Contentful.podspec

