language: objective-c
osx_image: xcode7.3.1
script:
- set -x -o pipefail
- xcodebuild -workspace Contentful.xcworkspace -scheme Contentful test -sdk iphonesimulator | xcpretty -c
- bundle exec slather coverage --coveralls Contentful.xcodeproj
- pod lib lint Contentful.podspec
