version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@1.6.2
  carthage: ngs/carthage@0.0.3

jobs:
  test:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-dep-{{ checksum "Cartfile.resolved" }}
      - ruby-orbs/bundle-install:
          bundle_clean: true
          bundle_extra_args: ""
          bundle_gemfile: Gemfile
          bundle_jobs: 4
          bundle_path: vendor/bundle
          bundle_retry: 3
          bundle_without: development test
          cache_key_prefix: v1-bundle
          restore_bundled_with: true
      - run: carthage build Contentful --no-skip-current --platform all --use-xcframeworks
      - save_cache:
          key: v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-dep-{{ checksum "Cartfile.resolved" }}
          paths:
            - vendor/bundle
            - Carthage
      - run: fastlane test
      - run: bundle exec slather coverage -s --coveralls
      - run: bundle exec pod lib lint Contentful.podspec

workflows:
  test-workflow:
    jobs:
      - test
